version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    ports:
      - "27017:27017"